SELECT *
FROM OPENROWSET(
    BULK 'FLIGHTS_2023.csv',
    DATA_SOURCE = 'flights_data',
    FORMAT = 'CSV',
    PARSER_VERSION = '2.0',
    HEADER_ROW = TRUE,
    FIELDTERMINATOR = ';'
)
WITH (
    FLIGHT_CARRIER_CODE VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    FLIGHT_NUMBER VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_1 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_2 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_3 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_4 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_5 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8
) AS t
WHERE FLIGHT_CARRIER_CODE = 'AF' AND FLIGHT_NUMBER = '0063' AND LEG_SCH_DEP_AIRPORT = 'EWR' AND LEG_SCH_DEP_DATE_UTC = '01/02/2023'


EXEC sp_describe_first_result_set N'SELECT *
FROM OPENROWSET(
    BULK ''FLIGHTS_2023.csv'',
    DATA_SOURCE = ''flights_data'',
    FORMAT = ''CSV'',
    PARSER_VERSION = ''2.0'',
    HEADER_ROW = TRUE,
    FIELDTERMINATOR = '';''
)
WITH (
    FLIGHT_CARRIER_CODE VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    FLIGHT_NUMBER SMALLINT,
    LEG_SCH_DEP_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_1 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_2 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_3 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_4 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_5 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8
) AS t;'

-- check doublons - DOUBLONS TO CLEAN
SELECT FLIGHT_CARRIER_CODE,
    FLIGHT_NUMBER,
    LEG_SCH_DEP_AIRPORT,
    LEG_SCH_DEP_DATE_UTC,
    count(*) as record
FROM OPENROWSET(
    BULK 'FLIGHTS_2023.csv',
    DATA_SOURCE = 'flights_data',
    FORMAT = 'CSV',
    PARSER_VERSION = '2.0',
    HEADER_ROW = TRUE,
    FIELDTERMINATOR = ';'
)
WITH (
    FLIGHT_CARRIER_CODE VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    FLIGHT_NUMBER VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_1 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_2 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_3 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_4 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_5 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8
) AS t
GROUP BY FLIGHT_CARRIER_CODE, FLIGHT_NUMBER, LEG_SCH_DEP_AIRPORT, LEG_SCH_DEP_DATE_UTC
ORDER BY record DESC;


-- Création de la vue
drop view Flights_2023_View

CREATE VIEW Flights_2023_View AS
SELECT *
FROM OPENROWSET(
    BULK 'FLIGHTS_2023.csv',
    DATA_SOURCE = 'flights_data',
    FORMAT = 'CSV',
    PARSER_VERSION = '2.0',
    HEADER_ROW = TRUE,
    FIELDTERMINATOR = ';'
)
WITH (
    FLIGHT_CARRIER_CODE VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    FLIGHT_NUMBER VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_1 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_2 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_3 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_4 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_5 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8
) AS t;

-- SELECT TOP 10 * FROM Flights_2023_View;

