SELECT *
FROM OPENROWSET(
    BULK 'FLIGHTS_2024.csv',
    DATA_SOURCE = 'flights_data',
    FORMAT = 'CSV',
    PARSER_VERSION = '2.0',
    HEADER_ROW = TRUE,
    FIELDTERMINATOR = ';'
)
WITH (
    FLIGHT_CARRIER_CODE VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    FLIGHT_NUMBER VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_1 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_2 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_3 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_4 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_5 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8
) AS t
ORDER BY LEG_SCH_DEP_DATE_UTC

-- Création de la vue
-- drop view Flights_2024_View

CREATE OR ALTER VIEW flights_View AS
SELECT
    NULLIF(TRIM(FLIGHT_CARRIER_CODE), '') AS FLIGHT_CARRIER_CODE,
    NULLIF(TRIM(FLIGHT_NUMBER),       '') AS FLIGHT_NUMBER,
    NULLIF(TRIM(LEG_SCH_DEP_AIRPORT), '') AS LEG_SCH_DEP_AIRPORT,
    NULLIF(TRIM(LEG_SCH_DEP_DATE_UTC), '') AS LEG_SCH_DEP_DATE_UTC,
    NULLIF(TRIM(LEG_SCH_DEP_TIME_UTC), '') AS LEG_SCH_DEP_TIME_UTC,
    NULLIF(TRIM(LEG_ACT_DEP_DATE_UTC), '') AS LEG_ACT_DEP_DATE_UTC,
    NULLIF(TRIM(LEG_ACT_DEP_TIME_UTC), '') AS LEG_ACT_DEP_TIME_UTC,
    NULLIF(TRIM(LEG_SCH_ARR_AIRPORT), '') AS LEG_SCH_ARR_AIRPORT,
    NULLIF(TRIM(LEG_SCH_ARR_DATE_UTC), '') AS LEG_SCH_ARR_DATE_UTC,
    NULLIF(TRIM(LEG_SCH_ARR_TIME_UTC), '') AS LEG_SCH_ARR_TIME_UTC,
    NULLIF(TRIM(LEG_ACT_ARR_DATE_UTC), '') AS LEG_ACT_ARR_DATE_UTC,
    NULLIF(TRIM(LEG_ACT_ARR_TIME_UTC), '') AS LEG_ACT_ARR_TIME_UTC,
    NULLIF(TRIM(LEG_DELAY_CODE_1),    '') AS LEG_DELAY_CODE_1,
    NULLIF(TRIM(LEG_DELAY_CODE_2),    '') AS LEG_DELAY_CODE_2,
    NULLIF(TRIM(LEG_DELAY_CODE_3),    '') AS LEG_DELAY_CODE_3,
    NULLIF(TRIM(LEG_DELAY_CODE_4),    '') AS LEG_DELAY_CODE_4,
    NULLIF(TRIM(LEG_DELAY_CODE_5),    '') AS LEG_DELAY_CODE_5
FROM OPENROWSET(
        BULK 'FLIGHTS_*.csv',
        DATA_SOURCE = 'flights_data',
        FORMAT = 'CSV',
        PARSER_VERSION = '2.0',
        HEADER_ROW = TRUE,
        FIELDTERMINATOR = ';'
)
WITH (
    FLIGHT_CARRIER_CODE VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    FLIGHT_NUMBER VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_DEP_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_AIRPORT VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_SCH_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_DATE_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_ACT_ARR_TIME_UTC VARCHAR(20) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_1 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_2 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_3 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_4 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8,
    LEG_DELAY_CODE_5 VARCHAR(10) COLLATE Latin1_General_100_CI_AS_SC_UTF8
) AS t;

-- SELECT count(*) FROM flights_View;